version: "3.9"

services:
  web:
    build:
      context: .
    command: ./bin/rails server -b 0.0.0.0 -p 3000
    volumes:
      - .:/app:cached
      - bundle:/bundle
    ports:
      - "11112:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_NAME: camaar_development
      RAILS_ENV: development
      BUNDLE_PATH: /bundle
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "11113:5432"

volumes:
  postgres-data:
  bundle:
